import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Providers from "./providers"; // <-- add this

export const metadata: Metadata = {
  title: "Airtable",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/airtable-favicon.ico?v=7" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={geist.variable}>
      <body>
        {/* Wrap the entire app so useSession() works anywhere */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
