import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata = {
  title: "Airtable",
  description: "Generated by create-t3-app",
  icons: {
    icon: [
      { url: "/icons/airtable-16.png?v=4", sizes: "16x16", type: "image/png" },
      { url: "/icons/airtable-32.png?v=4", sizes: "32x32", type: "image/png" },
    ],
    apple: [{ url: "/icons/airtable-180.png?v=4" }],
  },
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
